### ISSUE TITLE
LAC Helmet

### ISSUE THREAD

**Issue by KirchSabres15** [fewieden/MMM-NFL#12]
The LAC helmet does not have an image

**Comment by fewieden** [comment]
is the lac team the icon that is named la? or should there be a different one?

**Comment by bgibz** [comment]
The San Diego team moved to LA. The icons for SD should be used for LAC.

**Comment by fewieden** [comment]
@bgibz thanlks for the reminder, forgot about it, it should now be in the master branch as well
