### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by ruckus09** [fewieden/MMM-NFL#14]
Hello. I appologize in advance if I posted this in the wrong section. Please let me know where this should or shouldve been posted and I would be more than happy to fix it. 

My question however is I am trying to get my config file to work

This is what I have
		```
{
    			module: 'MMM-NFL',
    			position: 'top_right',
    			config: {
        			colored: "false"
    		},
```
I am trying to have it focus on the New York Giants and the Carolina Panthers. However I cannot seem to get it to work
If it is not too much trouble can someone show me a sample of their working code that I can edit to do what I want it to? 

Yes I see the config options but I dont know how to  write it in a way that my MM would display it. 

A bit of what I am going for. 

I am trying to get this screen to show all NFL stats in different sections of the screen. EG Scores for this week (Across the NFL) Standings (If possible but i dont think is possible) and Passing Yards. Thanks so much.

**Comment by ruckus09** [comment]
ok can I ask 2 questions?
1. How come its saying undined for the season as well as displaying the week the way it is now?
![moar](https://user-images.githubusercontent.com/15843447/35547890-e48053a0-0549-11e8-8da3-19d6619983a9.PNG)

Also 
Is there a way to just show the games the giants will play for 2018?

Thanks so much man! I appreciate the hell out of your response.

**Comment by fewieden** [comment]
1. The mode right now is set to ´PRO´ I'm only handling pre-season, season and postseason, so i need to add that. I guess the weeknumber is because you are using another language as supported by my custom translations ´de´ and ´en´.

2. There is no schedule integrated in that module

**Comment by ruckus09** [comment]
Ok cool I’ll check it tomorrow. Thanks a lot again. That would be a sick feature tho.

**Comment by fewieden** [comment]
If you have english or german as core language selected for your mirror, then it's a bug of magicmirror, that I could try to fix. If you have a different language, feel free to send me the language code and the translations for

```
{
"LOADING": "Loading...",
"HOME": "Home",
"AWAY": "Away",
"1ST_QUARTER": "1st Quarter",
"2ND_QUARTER": "2nd Quarter",
"3RD_QUARTER": "3rd Quarter",
"4TH_QUARTER": "4th Quarter",
"HALF_TIME": "Half Time",
"OVER_TIME": "Over Time",
"FINAL": "Final",
"FINAL_OVERTIME": "Final Over Time",
"TIE": "Tie",
"UPCOMING": "Upcoming",
"TIME_LEFT": "left",
"WEEK": "Week",
"BYE_WEEK": "Bye Week",
"PLAYER": "Player",
"TEAM": "Team",
"COMMAND_LIST": "List of all Voice Commands",
"MODE": "Mode",
"VOICE_COMMANDS": "Voice Commands"
}
```
