### ISSUE TITLE
Pulling Wrong Season

### ISSUE THREAD

**Issue by kevinb311** [fewieden/MMM-NFL#18]
I just did a fresh install of rasbian, magic mirror, and MMM-NFL. On start up of magic mirror, it looks like its trying to load preseason and then switches to 2017 regular season scores. Any ideas on what is causing that? 

On a semi related note, I also have MMM-NHL module installed, and that keeps loading as undefined undefined as well.

**Comment by fewieden** [comment]
I'm on vacation. But I checked and the data source is still providing the past season. It should be fixed automatically before the season starts and the provider switches the season on their side.

Please create an issue in MMM-NHL so i will not forget when I'm back home.

**Comment by justjim1220** [comment]
Same issue on my end also...

![screenshot 25](https://user-images.githubusercontent.com/27590633/44018644-1078d116-9ea2-11e8-99e5-adeaa7ced270.png)

**Comment by fewieden** [comment]
@justjim1220 as I said before, I have no control over the api to change to the new season, this change happens automatically by the vendor. I'm only in control over displaying you the data for the regular season or post season, as those are two different data feeds. Stay tuned as soon as the season starts the correct data should be displayed.

**Comment by dwleo** [comment]
The season has started but mine still shows 2017

**Comment by fuet143** [comment]
As @fewieden said, the current API is still pointed to 2017. I get the feeling they have abandoned the xml. [http://www.nfl.com/liveupdate/scorestrip/ss.xml](url)

I see a JSON api that is current:
[http://www.nfl.com/liveupdate/scores/scores.json](url)

Here are some examples game score records:
`"2018090912":{"home":{"score":{"1":0,"2":0,"3":3,"4":7,"5":0,"T":10},"abbr":"GB","to":3},"away":{"score":{"1":7,"2":10,"3":3,"4":0,"5":0,"T":20},"abbr":"CHI","to":3},"bp":6,"down":4,"togo":1,"clock":"12:46","posteam":"CHI","note":null,"redzone":false,"stadium":"Lambeau Field","media":{"radio":{"home":null,"away":null},"tv":"NBC","sat":null,"sathd":null},"yl":"CHI 34","qtr":"4"}`

`"2018090600":{"home":{"score":{"1":0,"2":3,"3":7,"4":8,"5":0,"T":18},"abbr":"PHI","to":1},"away":{"score":{"1":3,"2":3,"3":0,"4":6,"5":0,"T":12},"abbr":"ATL","to":0},"bp":10,"down":0,"togo":0,"clock":"00:01","posteam":"ATL","note":null,"redzone":false,"stadium":"Lincoln Financial Field","media":{"radio":{"home":null,"away":null},"tv":"NBC","sat":null,"sathd":null},"yl":"","qtr":"Final"}`

**Comment by fewieden** [comment]
@fuet143 do you have any information/experience with the json api? What about postseason/playoffs, I don't want to rewrite this module and need to do it in january again.

**Comment by dwleo** [comment]
Sorry, I am very new at this and have NO experience with the json api.

- Daryl

**Comment by fewieden** [comment]
nfl has updated the data and is now on week 2 season 2018

**Comment by sigel** [comment]
This still working for anyone?
