### ISSUE TITLE
Module not loading on mirror

### ISSUE THREAD

**Issue by raphfoe** [fewieden/MMM-NFL#19]
Hi all, 

Just started coding and took on the Magic Mirror as my first large project and really want to get this module running. I followed directions to clone,  included the module in my config file, ran the 'npm install --productive' line in the modules/MMM-NFL directory, but when I run my Magic Mirror, nothing shows up on the screen. 

I'm wondering if I need to include configs within the MMM-NFL module or if I need to remove other modules from the top_right portion.

Any help would be appreciated and apologize if this is a very basic issue.

Thanks!

**Comment by fewieden** [comment]
@raphfoe let me try to answer your questions:
1. Do you get any errors in the terminal where you run the magicmirror or pm2? Do you get any errors in the electron developer console (start the mirror with `npm start dev`)?

2. There is no config in the module required, only the global config file.

3. You don't need to remove other modules from this position, you can have multiple modules sharing the same position.

**Comment by raphfoe** [comment]
@fewieden thanks for helping me out! 
I'm not getting any errors and I kind of figured that I didn't need to config the module or remove other modules from the positions. I guess it would help if I explained what I'm doing step by step.

1. I went into my Magic Mirror > modules and typed "sudo git clone https://github.com/fewieden/MMM-NFL.git"
2. Went into my config file and added 
{
    module: 'MMM-NFL',
    position: 'top_right'
}
3. Went into Magic Mirror > modules> MMM-NFL and typed "sudo npm install --productive"
4. Started up my Magic Mirror but I just see every other module except MMM-NFL

Is it not showing up because I may not have the dependencies? If so, how would I go about installing those? 

Appreciate your time and looking forward to getting this module running!

**Comment by fewieden** [comment]
You don't have to use sudo for the commands, this could lead to permission problems.

You can check if the dependencies are there by scanning the node_modules directory in MMM-NFL

And when all other modules come up, but this doesn't I'm sure there are some errors in the places I posted above. If you can't find them you can contact me in a private message on the forum https://forum.magicmirror.builders/.

I just tried it myself and went through your steps and the module shows up for me.

**Comment by raphfoe** [comment]
Hi,

I deleted the MMM-NFL folder and tried doing everything from scratched, below are the steps I took:

pi@raspberrypi:~/MagicMirror/modules $ git clone https://github.com/fewieden/MMM-NFL.git
Cloning into 'MMM-NFL'...
remote: Counting objects: 326, done.
remote: Total 326 (delta 0), reused 0 (delta 0), pack-reused 326
Receiving objects: 100% (326/326), 540.67 KiB | 0 bytes/s, done.
Resolving deltas: 100% (174/174), done.
pi@raspberrypi:~/MagicMirror/modules $ cd MMM-NFL
pi@raspberrypi:~/MagicMirror/modules/MMM-NFL $ cd node_modules
bash: cd: node_modules: No such file or directory
pi@raspberrypi:~/MagicMirror/modules/MMM-NFL $ cd
pi@raspberrypi:~ $ cd MagicMirror
pi@raspberrypi:~/MagicMirror $ nano config/config.js.sample  <-- this is the file i run all modules through

included the below in the config file
 {       module: 'MMM-NFL',
                        position: 'top_right'
                },

pi@raspberrypi:~/MagicMirror $ cd modules
pi@raspberrypi:~/MagicMirror/modules $ cd MMM-NFL
pi@raspberrypi:~/MagicMirror/modules/MMM-NFL $ npm install --productive
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
mmm-nfl@1.0.0 /home/pi/MagicMirror/modules/MMM-NFL




I'm wondering if perhaps my MM needs to be updated?

**Comment by fewieden** [comment]
the mirror loads the config/config.js file not config/config.js.sample, other than that it looks fine to me

**Comment by fewieden** [comment]
Closed due to inactivity
