### ISSUE TITLE
not showing correct day & time of the games

### ISSUE THREAD

**Issue by justjim1220** [fewieden/MMM-NFL#20]
the day and time only shows the actual current day and time and NOT the day and time of the games

![screenshot 76](https://user-images.githubusercontent.com/27590633/46242382-192dbb80-c38e-11e8-9155-351c7cd107b6.png)

**Comment by fewieden** [comment]
With the default module config I can't reproduce your problem, it's showing me the times in my current timezone.

```
{
	module: 'MMM-NFL',
	position: 'top_right'
}
```
![nfl](https://user-images.githubusercontent.com/9334168/46243137-ed7ff500-c3d0-11e8-80d8-04e007271003.PNG)

**Comment by justjim1220** [comment]
I just re downloaded and installed a fresh module, straight from here.
the colors and fonts are from my custom css file for the mirror.

I get the same outcome. Don't know why, But, maybe it will work itself out somehow.
I do know that it was working just fine until a few days ago.

![screenshot 77](https://user-images.githubusercontent.com/27590633/46243258-db359500-c397-11e8-8f89-3a7ec2d861b6.png)

**Comment by fewieden** [comment]
Can you post me your nfl config? Maybe moment is interfering with another module?

**Comment by justjim1220** [comment]
`{
			disabled: false,
			module: "MMM-NFL",
			position: "top_right",
		},`

**Comment by justjim1220** [comment]
{
			disabled: false,
			module: "MMM-NFL",
			position: "top_right",
		},

**Comment by justjim1220** [comment]
I have a lot of issues with some modules interfering with other modules

especially those modules that are an image, IE: easypic, eyecandy, backgroundslideshow, dailydilbert, simplelogo, earth, globe, ISS, mars, moon-phases, nasaastropic, random photo, et al.

they especially interfere with CalendarEXT, my YouTube module, AVStocks, and a few others.

Each one that I have tried will either show or not show, as well as the modules they interfere with

**Comment by justjim1220** [comment]
so I guess I will disable modules to see which one is interfering with the NFL one

**Comment by justjim1220** [comment]
I have 6 pages of modules...

![screenshot 78](https://user-images.githubusercontent.com/27590633/46243670-8d6f5b80-c39c-11e8-9d1b-f3391b447f6a.png)
![screenshot 79](https://user-images.githubusercontent.com/27590633/46243695-93fdd300-c39c-11e8-976d-f9e1320d5248.png)
![screenshot 80](https://user-images.githubusercontent.com/27590633/46243697-9b24e100-c39c-11e8-86e3-61913ebc9e44.png)
![screenshot 81](https://user-images.githubusercontent.com/27590633/46243702-a2e48580-c39c-11e8-9723-2f3f5ea2ae00.png)
![screenshot 82](https://user-images.githubusercontent.com/27590633/46243708-ab3cc080-c39c-11e8-8181-32843960815f.png)

The Last one is used for testing and currently blank with no modules assigned to it.

**Comment by justjim1220** [comment]
after disabling all modules, rebooting my PC, no change.

Deleted the NFL module, re-downloaded and installed it, made sure it was the only module not disabled, including alert and notification. 

NOW, it's working!!!

So, I guess I will start enabling each module one-by-one to see which one is interfering with it.

**Comment by fewieden** [comment]
Keep me posted when you figured out which module is causing the problem with this one.

**Comment by justjim1220** [comment]
None of them fixed the issue.

I ended up, deleting the module, rebooting the laptop, then reinstalling the module.

Now it works! Have no idea what the problem was, But the same thing happened to the MMM-GAS module, did the same thing and it now works!

**Comment by justjim1220** [comment]
I do have a question...

How do I get all these statistics in the code to show, I don't have voice control, so it rides on me being able to click on something. I'm kind of interested in seeing what it does and the stats it shows, and how to get them to show up. Also, is that option only for the focus_on?

**Comment by fewieden** [comment]
Statistics cannot be used without voice.

It shows data from this page http://www.espn.com/nfl/statistics. If one of the players is part of your team (focus_on) he will be highlighted.

**Comment by justjim1220** [comment]
OK, Thanks for letting me know...

It's still an awesome module!
