### ISSUE TITLE
2 Requests: Reverse Home and Away, Fix LA to LAR. 

### ISSUE THREAD

**Issue by BKeyport** [fewieden/MMM-NFL#22]
Please reverse Home and Away. The Home team should be listed second - for example this week:  SEA @ LA. Only sport I know of that puts home first is international football (Soccer) 

Also, because there's two teams in Los Angeles, Is it possible to fix "LA" (LA Rams) to indicate LAR like most/all broadcasts refer to them as? (LAC being the other) - makes it a ton easier to tell who is who at a glance without studying the logo/helmet. 

Thanks!

**Comment by BKeyport** [comment]
Wow - That's beyond weird that the NFL would list the scores backwards like that and LAR as LA. 

Thanks for the info.

**Comment by fewieden** [comment]
You can test the config option to reverse teams now https://github.com/fewieden/MMM-NFL/pull/24

1. Go to the module directory `cd ~/MagicMirror/modules/MMM-NFL`
2. Change to the develop branch `git checkout develop`
3. Test and report

**Comment by BKeyport** [comment]
#26 Confirmed working. Thanks!

**Comment by BKeyport** [comment]
EEEP! I was wrong, the possession ball is still on the left for the home team, right for the away team.

**Comment by fewieden** [comment]
@BKeyport it should be fixed now on develop branch, thanks to @justjim1220

**Comment by BKeyport** [comment]
Yes, I marked this closed as the other area #24 covered it. Thanks to both of you.

**Comment by justjim1220** [comment]
😎
