### ISSUE TITLE
Bad date handling? 

### ISSUE THREAD

**Issue by BKeyport** [fewieden/MMM-NFL#23]
Module is reporting "Invalid Date" on 1st thanksgiving game: 

g eid="2018112200" gsis="57728" d="Thu" t="12:30" q="P" h="DET" hnn="lions" hs="0" v="CHI" vnn="bears" vs="0" rz="0" ga="" gt="REG"/

**Comment by fewieden** [comment]
yes you're right there is a problem with handling the date. I assumed that the NFL would report that as 0:30 instead of 12:30 this destroys my date time conversion. Unfortunately I don't think that I will be able to fix this before the game starts.

**Comment by cowboysdude** [comment]
Well that's because in the US games are displayed in Eastern Standard Time 12 hour format.  It can be converted to 24 hour time but why?

**Comment by BKeyport** [comment]
Ahh, see, and the game time was actually 12:30pm Eastern Time. All major sports in the US center on New York time, then adjust from there - Dumbass Standard Time included. 

Here's what we know from the NFL feed: 
Times are shown in eastern time zone's current offset (-5 or -4 from UTC)  
Times are in a 12 hour clock
Times do not include AM/PM 
Typical Monday and Thursday games are nighttime games (8pm eastern) 
Typical Sunday games start no earlier than 1pm.
Known exceptions: 
London Series games are usually morning games (eastern time) The three this year were 1pm, and 9am hour games (I think they were like 1:15p, 9:30a, and 9;30a)  
Thanksgiving games are all day affairs (12:30, 4:30, 8:20). 

That's all the time cases I know about.

**Comment by BKeyport** [comment]
Oh, and the mexico game (which moved to LAR) is within the range of typical, if I recall right.

**Comment by BKeyport** [comment]
https://operations.nfl.com/the-game/creating-the-nfl-schedule/

**Comment by BKeyport** [comment]
Yeah, I covered all the oddities I could think about... then on my drive to work I realized - Saturday Games. Totally off schedule, too.

**Comment by cowboysdude** [comment]
The issues that there are so many oddities involved.
<g eid="2018123001" gsis="57808" d="Sun" t="1:00" q="P" h="BUF" hnn="bills"
hs="0" v="MIA" vnn="dolphins" vs="0" rz="0" ga="" gt="REG"/>

That is all you can do is work from this information.  The ONLY other way
is to scrap the data from a page but from year to year they change how they
do things so that's not practical at all.

**Comment by BKeyport** [comment]
Went through the 2018 schedule, and here's what I found for every game: 
Times as published were/are: 9:30a, 12:30p, 1:00p, 4:05p, 4:25p, 4:30p, 7:10p, 8:15p, 8:20p and 10:20p,
(Eastern Time Zone) 

I can't think of any way to logic through this without an AM/PM indicator in the data.

**Comment by cowboysdude** [comment]
I agree.  So what I would do is either use the literal time OR just put
down 'Early Game', "Late Game', "Monday Game", Sunday Night Game",
"Saturday Game".......

**Comment by fewieden** [comment]
Ideally I would like to get rid of the xml endpoint anyways because in a couple of days there will be another temporary bug with flickering between regular and post season.

I think I might switch to the json endpoint http://www.nfl.com/liveupdate/scores/scores.json in the new module version
+ easier to implement than xml
+ will automatically switch between regular and post season (1 bug fixed)
- doesn't contain any time information, only the day. Which wouldn't be a problem for users who live in the same timezone, or close to it. But for users like me (european timezone) half of the games would display the wrong day if i would just show `Thu`, the games here are always friday morning.

**Comment by cowboysdude** [comment]
json scorestrip doesn't have a reg and postseason variant......it only has
that one so yes it would fix the change over issue.

**Comment by BKeyport** [comment]
I personally wouldn't care if the module just said "National Football League" for the header - there's no reason to show pre/regular/post season.

**Comment by BKeyport** [comment]
Wow, that's one hell of a changover bug. Just caught that this morning leaving for work. Man, I can see why you want to change it. 

:)

**Comment by cowboysdude** [comment]
Well for some VAST reason the NFL delays everything by a day or
so.........they should populate the playoff xml within an hour after the
reg season but hey what do I know....

**Comment by BKeyport** [comment]
Hell, the media was reporting the playoff schedule before the 2nd shift games started. 

I guess this is what we get for using data "not meant for us" eh?

**Comment by cowboysdude** [comment]
Lol

**Comment by fewieden** [comment]
I thought about it again. I'm not sure anymore if changing the source is the best idea. Because if we don't have the starting times, then we will loose complete support of the live feature :/

Any ideas how we should handle it?

**Comment by BKeyport** [comment]
only thing I can think of at this point is different source, like ESPN. Was poking around, and ESPN's feed for NFL is http://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard  - Times are shown as zulu, it looks like, but it looks to be a total train wreck otherwise. 

There seems to be methods to cut it down, per other modules like MMM-MyScoreboard - but the reason I use yours over his is that he only shows one date - and don't want to switch, where you show the entire week schedule. 

From his code:
        //    "http://site.api.espn.com/apis/site/v2/sports/" +
        //     this.getLeaguePath(league) +
        //     "/scoreboard?dates=20180317" +
        //     "&limit=200";

**Comment by fewieden** [comment]
@BKeyport the module is now using the ESPN API
