### ISSUE TITLE
Stuck in loading

### ISSUE THREAD

**Issue by rixmix123** [fewieden/MMM-NFL#30]
The module is stuck in loading mode. Any ideas?

**Comment by fewieden** [comment]
@rixmix123 sorry for the late response. I just installed the newest version of the module and it started showing me the data from the postseason just fine.

There could be multiple reasons:
- Connection problems
- Dependencies not installed
- Error is thrown
- ...

I suggest taking another look when the new season starts and if you have the same issues to report again and/or check out the forum for more help.

**Comment by mrpicasso** [comment]
module stuck in loading... not sure what could be the issue
