### ISSUE TITLE
Bye Week Display Issue

### ISSUE THREAD

**Issue by gabrielm9999** [fewieden/MMM-NFL#37]
Hello - First of all, many thanks for this module.  It's the most popular one in my household with 2 boys eagerly following their favorite teams.  

An issue popped up this morning at the start of Week 5.  The Packers are on their bye week.  The date/time column now displays "Week {weekNumber} 5".  One would expect that column to display "Bye Week".  I have reverseTeams set to true.  Disabling that setting makes no difference.

![MMM-NFL](https://user-images.githubusercontent.com/72508332/95343113-27204c00-0886-11eb-81b1-56e950a6ba30.jpg)

config.js:
```		
               {
			module: 'MMM-NFL',
			position: 'top_center',
			config: {
				colored: true,
				helmets: false,
				focus_on: ['SEA', 'GB', 'NYG', 'NYJ'],
				reverseTeams: true,
			}
                 },
```
There are no custom.css settings.  This isn't a huge issue but I though I'd report it anyway.

Thanks...

**Comment by fewieden** [comment]
@gabrielm9999 thanks for reporting the issue I will look into it.

**Comment by fewieden** [comment]
@gabrielm9999 I just fixed the bye week rendering. Problem was that the translation label "WEEK" was changed in the core to contain the week number after I created this 3 years ago. If you don't focus on a team you will never see the issue.

Also, I feel with your family. I'm also suffering from the Giants :D

**Comment by gabrielm9999** [comment]
@fewieden Awesome.  Thanks for the fix.  I will pull the dev branch when I get a chance.

Yes, the Giants have been a disappointment, but my kids have "backup" teams they've been cheering for a while.  It helps!

**Comment by fewieden** [comment]
@gabrielm9999 the change is already on the master branch
