### ISSUE TITLE
Game times

### ISSUE THREAD

**Issue by ESOB86** [fewieden/MMM-NFL#4]
I am on EDT and game times are reported 1 hour after kickoff (i.e. 2:00pm for a 1:00pm game).  

For more information, my raspberry pi is configured to area: America, location: New_York.

**Comment by fewieden** [comment]
the kickoff times are provided in est timezone (utc-5) and after a lookup edt is summertime (utc-4) that's why moment.js converts the time to 2pm

**Comment by ESOB86** [comment]
I think the source for your game times is actually reporting in EDT (UTC-4) right now.  If you look up what time the Ravens vs Buffalo game is on the east coast it will list at 1300 Eastern which is EDT, not EST. 

Either way, If the module only reports 1 hour off until the end of daylight savings time it is still an awesome module.  Thanks for making this.

**Comment by fewieden** [comment]
The source is http://nfl.com

Strange thing is with the current setup the times get correctly converted to my timezone (utc+2). If the source would be utc-4 it would be an hour off for me, but I will have a deeper look into this

**Comment by ESOB86** [comment]
I can confirm those times are listed as Eastern US time which is EDT right now (which will change back to being listed as EST on November 6th).

**Comment by fewieden** [comment]
I will work on this branch tonight so we can check if it is working then for everyone, before merging into master

https://github.com/fewieden/MMM-NFL/tree/bugfix/time-conversion

**Comment by ESOB86** [comment]
I tried to checkout the new branch and it turned the magic mirror output just straight white.

**Comment by fewieden** [comment]
cd ~/MagicMirror/modules/MMM-NFL
git fetch
git checkout bugfix/time-conversion
npm install

**Comment by ESOB86** [comment]
Thanks for the assistance with git.  The times appear correctly now.  

When you merge this back into the main branch if you could give the commands to execute that would be awesome.  

Again thanks for the module and the quick responses.

**Comment by fewieden** [comment]
i will wait one day to get more feedback on the forum and then I will merge it in master, then you have to type the following:

cd ~/MagicMirror/modules/MMM-NFL
git checkout master
git pull

**Comment by ESOB86** [comment]
I would have posted the issue there but it won't send me the confirm email.  Also when I found an issue in MMM-traffic I got really good response from the creator on github.

**Comment by paviro** [comment]
Confirm email should work again :)
