### ISSUE TITLE
2021 Season (prototype for new API provider available)

### ISSUE THREAD

**Issue by k-samani** [fewieden/MMM-NFL#44]
Today is the start of a new season. I have noticed that this module is not updating. Any suggestions? I tried to update url but saw that it does not exist or I don't have access to. Any help is appreciated.

**Comment by fewieden** [comment]
@k-samani this is a known issue with this API.

The pre-season was never covered. In the previous years, it showed the old season until the first or second matchday of the regular season. After that the update worked normal again.

**Comment by k-samani** [comment]
Understood. With this code, it is showing "NFL REGULAR SEASON 2021 WEEK UNDEFINED" and "Loading" under it. So, when the regular season starts, it should correctly pull the data?

**Comment by jupadin** [comment]
Given the current endpoint api (http://static.nfl.com/liveupdate/scorestrip/ss.xml) you only get the games from last season, week 17.

I also heard some rumors that the closed the API and that the data for the new season won't be longer available.
Hopefully this is only a rumor and does not reflect the current situation...

In case you get any data for the new season, please let me know - I'm also interested if there are new updates regarding the API.

**Comment by k-samani** [comment]
I did another git clone and this is what is showing ...sorry for bad picture...I'll wait until the season starts and see if it updates

![20210816_145543.jpg](https://user-images.githubusercontent.com/75324271/129622063-6a32600e-514e-4efb-afce-3a3f9fc0e1b3.jpg)

**Comment by jupadin** [comment]
Despite waiting until the new season starts, there should be data available anyways.
Seems like - quick reviewing the code - there is somewhere an error, since both urls in node_helper.js return data.

As long as both urls do not return any data regarding the new season or having another api available, there is not much hope i guess...

**Comment by fewieden** [comment]
@k-samani @jupadin as mentioned before the API is always behind until the season starts. There are various forums reporting over no data every year. So far it always was up-to-date from matchday 1 or 2. In one extreme case, I think it was already matchday 5-7.

There was once a valid alternative with JSON data structure, which would simplify the logic of this module, but it lacked the information so I didn't move on.

Regarding your screenshot. I just had a look in my developing machine and this is how it looks for me:

![image](https://user-images.githubusercontent.com/9334168/129673165-70ded2b3-df20-4844-a8d2-f6438fe2c791.png)

Can you check if you get any errors in the developer console (press ctrl + shift + i for electron) and the nodejs logs in the terminal.

**Comment by jupadin** [comment]
@fewieden, thank you for this clarification. I'm reassured by that and am even more eagerly awaiting the start of the season.

The JSON option with the missing start times is actually very impractical and not usable in use or with the purpose of the module.

**Comment by Plainbroke** [comment]
Sooooo,
What are you saying in  MagicMirror modules for dummies language?

**Comment by fewieden** [comment]
@Plainbroke can you point out which part was not understandable for you and I will try to explain it in different words

**Comment by jfc0316** [comment]
Has any progress been made on this? Mine still does not update with the 2021 data and still shows last game of last season. How do you update?

**Comment by fewieden** [comment]
@jfc0316 the API still returns the data for the previous season

**Comment by jfc0316** [comment]
Do you know if they have plans to fix or not?

Jason Cox

**Comment by DukeX21** [comment]
when will the update for the regular season come. When loading, 2021 will be displayed. But if the games are loaded, they are from week 17 on 2020

**Comment by cowboysdude** [comment]
NFL no longer giving that data for free apparently...... sad really they make 5 billion dollars a year you'd think they would continue that.....

**Comment by k-samani** [comment]
I created a code in Python. Would it be useful? I know Magic Mirror uses Node.js but would it be difficult to convert? I have very little experience with Node.js.  But here is what I came up with >> https://github.com/k-samani/NFL_score_pyton.git

**Comment by fewieden** [comment]
I will try to build a prototype with the ESPN API on Sunday.

**Comment by Plainbroke** [comment]
Oh, Thank You.  My wife and I both like the NFL scoreboard

Jeff Burdick

**Comment by jfc0316** [comment]
That would be awesome if you could! I keep thinking one of these weekends I will look and see it updated, no dice thus far! 😩

Jason Cox

**Comment by fewieden** [comment]
@k-samani @jupadin @Plainbroke @jfc0316 @dantheman369 @DukeX21 @cowboysdude I already have something working. I tried to make the minimal required changes to make this work asap. Once we find the most issues, there is a lot of work ahead to get this module in shape again. This was one of my first modules and I would probably rewrite it from scratch.

It looks like finished and scheduled games are working so far.

![nfl](https://user-images.githubusercontent.com/9334168/135709812-003e4a42-fcb4-429e-b7a7-a31ff5bf3ce5.png)

Tested:
- [x] Scheduled games
- [ ] Live games (game period, remaining time in quarter, score)
  - [ ] Current quarter
  - [ ] Remaining time in quarter
  - [ ] Overtime
- [x] Finished games
- [ ] Preseason
- [ ] Postseason
- [ ] Super Bowl
- [ ] Offseason
- [ ] Switching automatically to next game week
- [ ] Switching automatically to post season
- [ ] Voice commands to display statistics

Unsupported:
- [ ] Fetching data (every minute) during live games

I would like to ask you to test the module yourselves with your config options to find other possible issues and also keep an eye out during live games.

If you already have the module installed you can try the prototype by executing the following commands.

```bash
cd ~/MagicMirror/modules/MMM-NFL
git checkout develop
git pull
npm install --production
```

I also suggest enabling the default module `updatenotification` to see on the mirror that the prototype has an update available.

**Comment by jfc0316** [comment]
Hey! And thanks again! I was so excited to wake up this morning and see that you already had some thing up and running! 

I tried it this morning and this is the error message that I got. 



Jason Cox

**Comment by fewieden** [comment]
@jfc0316 your message doesn't contain an error. Can you try posting it again via Github instead of mail

**Comment by k-samani** [comment]
I get the following when I do git checkout develop and try to git pull:

![image](https://user-images.githubusercontent.com/75324271/135725896-d326875a-9d85-486f-a891-673e0c41eecb.png)

**Comment by k-samani** [comment]
got it to pull. i did a 'git reset --hard' and 'git pull' and it updated. 
![image](https://user-images.githubusercontent.com/75324271/135726057-006faf29-0195-4798-9415-daeb37d36109.png)

**Comment by k-samani** [comment]
I am just having a hard time figuring out what I need to update in the updatenotficatiion.

**Comment by k-samani** [comment]
is it this part >> `moduleList: {},` ?

**Comment by jfc0316** [comment]
@fewieden @k-samani  I was having the exact same issue but I think mine might go a little deeper.  I am seeing issues with alot of modules and I am noticing that everything modules ends up at "node-gyp-build" freezes for a second, and then eventually ends up as an error.

**Comment by jfc0316** [comment]
scratch that, it's working! Thanks @fewieden and @k-samani 
Now I've got to figure out what's wrong with the MMM-Detector module.  I think the node-gyp-build error is related to that ....

**Comment by fewieden** [comment]
@k-samani you don't need to modify the module. Simply add the following to your config.js file

```
{
  module: "updatenotification",
  position: "top_bar"
},
```
it will automatically scan the git repositories of all your installed modules

**Comment by k-samani** [comment]
Thank you.

**Comment by fewieden** [comment]
During the live games, they changed the order of the games. Sorting now always by date to have the finished games at the top.

![1st quarter](https://user-images.githubusercontent.com/9334168/135764867-e056ad4b-1d4c-45f7-81f5-505481701c5f.png)

**Comment by k-samani** [comment]
Seems like it is updating live. I have mine set to 3 minutes.
![20211003_123229.jpg](https://user-images.githubusercontent.com/75324271/135765007-76679734-2365-46d3-907d-ce69c0712c6f.jpg)

**Comment by k-samani** [comment]
And it pushed the finished game at the bottom which is fine by me

**Comment by fewieden** [comment]
@k-samani yeah but Monday Night Football was still listed after the finished game.

Displaying now also halftime status

![halftime](https://user-images.githubusercontent.com/9334168/135766945-7e483ef7-7f62-4b2e-85c6-23379a84f41c.png)

**Comment by k-samani** [comment]
I think it goes by day. I think it will update the order tomorrow. Speaking of update, mine stopped updating the scores. I quit Magic mirror and do not start, it updates the scores initially but not after

**Comment by fewieden** [comment]
@k-samani but Bengals vs. Jaguars was already Thursday Night Football, it shouldn't be mixed with Sunday.

It is still updating for me. Do you see any logs in the electron console or terminal?

Now also with support for overtime

![overtime](https://user-images.githubusercontent.com/9334168/135770566-c320eb44-5ae2-4146-b186-9e458ab983fd.png)

**Comment by k-samani** [comment]
I don't see any

**Comment by k-samani** [comment]
did a git pull and something changed... probably something i messed up
`pi@raspberrypi:~/MagicMirror/modules/MMM-NFL $ git pull
From https://github.com/fewieden/MMM-NFL
   d2068a9..baf1f35  develop    -> origin/develop
Updating d2068a9..baf1f35
Fast-forward
 espn.js | 16 +++++++++++++++-
 1 file changed, 15 insertions(+), 1 deletion(-)
`

**Comment by fewieden** [comment]
@k-samani the last part is caused because I made commits during the live games

![commits](https://user-images.githubusercontent.com/9334168/135803818-a683343a-d254-4fe4-b2d0-34331a4698ab.png)

**Comment by k-samani** [comment]
Gotcha..worked after I did gut pull

**Comment by k-samani** [comment]
Thank you for getting this fixed. Not sure if my python helped any but thank you.

**Comment by jfc0316** [comment]
Absolutely second that!!! Thank you so much!

Jason Cox

**Comment by fewieden** [comment]
Bye weeks are also working as before

![bye week](https://user-images.githubusercontent.com/9334168/137435987-d2171e5a-8007-4e7d-8b13-fb4bb6dd3628.png)

**Comment by fewieden** [comment]
Bye weeks are also working as before

![bye week](https://user-images.githubusercontent.com/9334168/137436138-e73b1dd8-2272-4c5b-b037-3b51a91eadaf.png)

**Comment by k-samani** [comment]
is there an option for the teams with bye week to show up? I did a git pull and mine doesn't show bye week.
![image](https://user-images.githubusercontent.com/75324271/137437669-e2fcd764-da0f-4adf-948c-bd2e2d4e309a.png)

**Comment by jupadin** [comment]
yeah, it should be the `focus_on` option. There you can specify an array of strings (["GB", "NE", ...]) for which the bye week should be shown...

**Comment by k-samani** [comment]
Makes sense. Thank you.

**Comment by MiTechneek** [comment]
Please be patient with me here, this is my first time commenting on github. For the most part I've been able to fix my issues with some deep soul searching, and persistent internet combing. This time, however, I am at a loss. I've followed the instructions to a T everything seems to be going correctly. Then I get a message that I need to audit fix. After I enter the command

**Comment by MiTechneek** [comment]
Please be patient with me here, this is my first time commenting on github. For the most part I've been able to fix my issues with some deep soul searching, and persistent internet combing. This time, however, I am at a loss. I've followed the instructions to a T everything seems to be going correctly. Then I get a message that I need to audit fix. After I enter the command, the same 3 vulnerabilities return to be npm audit fix'd again. When I run magic mirror I get 2022 season... undefined. If I try and tweak anything it reverts back to 2021 week 17.
What stupid thing am I doing!?!?! 

Thanks for any help
![20220111_133101](https://user-images.githubusercontent.com/97546644/149001108-260ddae0-ee0a-4c48-900b-0f839b140d30.jpg)
![20220111_133139](https://user-images.githubusercontent.com/97546644/149001126-4224a93e-8188-4743-a6d5-202772ef5b34.jpg)
![20220111_133507](https://user-images.githubusercontent.com/97546644/149001138-2fb0975b-fc57-49bb-bb76-d8b260ec7c90.jpg)
![20220111_132828](https://user-images.githubusercontent.com/97546644/149001147-aee36f6b-dcc8-4746-a3ed-692e2627444c.jpg)

**Comment by MiTechneek** [comment]
> Please be patient with me here, this is my first time commenting on github. For the most part I've been able to fix my issues with some deep soul searching, and persistent internet combing. This time, however, I am at a loss. I've followed the instructions to a T everything seems to be going correctly. Then I get a message that I need to audit fix. After I enter the command, the same 3 vulnerabilities return to be npm audit fix'd again. When I run magic mirror I get 2022 season... undefined. If I try and tweak anything it reverts back to 2021 week 17. What stupid thing am I doing!?!?!
> 
> Thanks for any help ![20220111_133101](https://user-images.githubusercontent.com/97546644/149001108-260ddae0-ee0a-4c48-900b-0f839b140d30.jpg) ![20220111_133139](https://user-images.githubusercontent.com/97546644/149001126-4224a93e-8188-4743-a6d5-202772ef5b34.jpg) ![20220111_133507](https://user-images.githubusercontent.com/97546644/149001138-2fb0975b-fc57-49bb-bb76-d8b260ec7c90.jpg) ![20220111_132828](https://user-images.githubusercontent.com/97546644/149001147-aee36f6b-dcc8-4746-a3ed-692e2627444c.jpg)

Follow up... I'm an idiot it works
Thx for this thread!!  I will now fade back into the shadows

**Comment by fewieden** [comment]
Thanks, everyone for testing. I released it now to the master branch. You can switch your branch again by

```bash
cd ~/MagicMirror/modules/MMM-NFL
git checkout master
git pull
npm install --production
```
