### ISSUE TITLE
Stuck showing Bye Week for the Commanders and Rams When Using Multiple Configurations of the Module?

### ISSUE THREAD

**Issue by BerkSmash1984** [fewieden/MMM-NFL#64]
Platform (Hardware/OS):
RPI 4
Debian GNU/Linux 11 (bullseye)

Node version:
v20.17.0

MagicMirror version:
Latest

Module version:
Latest

Description of the issue:
Only for the Washington Commanders and the LA Rams, they have 2 separate entries showing bye week despite also showing correctly scheduled games on a separate config:

![image](https://github.com/user-attachments/assets/bf8b17ed-16da-4fd0-a094-70223306b6f5)

Here is my MM config, in which I have the MMM-NFL module configured in 4 separate instances, so that I can use it with MMM-Pages and fit all teams across 2 separate pages:

![image](https://github.com/user-attachments/assets/8cbaf6b7-4aae-4245-b424-7d7eaaf1b90e)

Any ideas?

**Comment by fewieden** [comment]
@BerkSmash1984 you used the wrong team codes in your config

![image](https://github.com/user-attachments/assets/c31867b4-2363-4c96-be44-ab4ca2558c66)

**Comment by BerkSmash1984** [comment]
Oof, good catch! I must have been referring to an old name code. Will mark this as closed. Thanks!
