### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by vwbusdriver** [fewieden/MMM-NFL#7]
The module shows up, but it is displaying NFL Pre-Season when it should be Regular Season, and it also just says "loading..." and is not showing any data. Any help would be much appreciated.

Thank you

**Comment by fewieden** [comment]
it says pre-season as a default until data is loaded.

do you get any errors in the terminal or electron console?

**Comment by vwbusdriver** [comment]
I was not getting any errors in terminal or electron thats why I was confused. I am fairly new to git hub so I cleared everything and started over. It still didn't load for me so I decided to take a break. When I rebooted it was there and working correctly.  Awesome module and looks great! (this was about the 4th time trying to get this to work) 
Thank you for the quick response fewieden!
