### ISSUE TITLE
Switching to Post season

### ISSUE THREAD

**Issue by The1337Stick** [fewieden/MMM-NFL#9]
I do not see the mode automatically switching from regular season to post season.  I updated the mode to post from regular that is in the node_helper.js.  It looked like it was supposed to do this automatically.

**Comment by fewieden** [comment]
Yes intentionally it should switch automatically, but I was not aware on how the data will look like in the post season. As it turned out, it will not increase to week 18, so I have to adjust the check for the automatically switch

**Comment by fewieden** [comment]
fixed please update

**Comment by Jt4112** [comment]
I'm just gonna post my question here, so I don't create a new issue. 

Would it be possible to turn this into an All American Sports Module? All of the NFL, NHL, MLB,  ESPN pages are all identical (or very similar). Another idea could be a future option to view only a specific team? If I only watch the Steelers(NFL), Pirates(MLB) and Penguins(NHL),  I'd only want to display those games. Or if you left it with just NFL, only display the Steeler's Schedule and Scores.

Thanks, JT

**Comment by fewieden** [comment]
Did you try the focus_on option for the Steelers?

There is also a NHL module, checkout my other repositorys.

I don't think I will put your ideas into this module, but maybe I will create another module for this in the future.

**Comment by Jt4112** [comment]
Oh didn't even notice that. Great work.

**Comment by fewieden** [comment]
just fixed a bug which occured on magicmirror restart since february
